--- 
title: "Pronóstico de Ventas de Café en Máquinas Expendedoras"
author: "Luisa Angélica Isaza Sanabria - Juan Andrés Murillo Cadena - Carlos Fabián
  Villa Infante"
date: "`r Sys.Date()`"
output: pdf_document
documentclass: book
bibliography:
- book.bib
- packages.bib
description: |
  This is a minimal example of using the bookdown package to write a book.
  set in the _output.yml file.
  The HTML output format for this example is bookdown::gitbook,
link-citations: true
github-repo: "rstudio/bookdown-demo"
site: bookdown::bookdown_site
---

# Introducción 2

Durante este curso de series de tiempo, hemos decidido trabajar las ventas de café en una máquina expendedora. Detrás de cada café que alguien compra en su lugar de trabajo o en un espacio público, hay patrones de consumo, hábitos y decisiones que se repiten en el tiempo. Analizar esta información nos permite aplicar modelos de pronóstico reales, útiles y con impacto directo en la toma de decisiones comerciales y operativas.

Poder anticipar cuánto café se va a vender en los próximos días, semanas o meses es  clave para mejorar la experiencia del cliente, reducir pérdidas y aumentar la eficiencia.

## Justificación de la Elección

El café es una de las bebidas más consumidas en todo el mundo, y las máquinas expendedoras son una forma práctica de acceder a él. Nos pareció un caso ideal porque:


	1.	Ayuda a planificar mejor los inventarios: Prever la demanda permite tener siempre lo justo: ni mucho producto que termine vencido, ni tan poco que dejemos de vender.

	2.	Hace más eficientes las operaciones: Si sabemos cuándo se vende más café, podemos organizar mejor las recargas y los mantenimientos, ahorrando tiempo y dinero.

	3.	Permite personalizar promociones:Detectar días u horarios de baja demanda ayuda a lanzar promociones en momentos estratégicos.

	4.	Mejora la experiencia de quienes compran: Asegurar que los productos favoritos estén disponibles en los momentos clave mejora la satisfacción y fideliza al cliente.


## Descripción de la Información a Utilizar

Vamos a utilizar un dataset llamado “Coffee Sales”, publicado por Yaroslav Isaienkov en la plataforma Kaggle. Esta base de datos contiene registros reales de ventas desde marzo de 2024 y sigue actualizándose semanalmente.

El dataset incluye:

	•	La fecha y hora de cada transacción
	•	El tipo de café vendido
	•	La cantidad y el método de pago
	•	Información detallada sobre el producto y las preferencias del cliente

Todo esto en archivos están en formato .csv que son muy fáciles de trabajar y analizar, ideales para aplicar modelos de series de tiempo.

## Fuentes y Permisos de Uso

Una gran ventaja de este dataset es que está disponible bajo una licencia de dominio público (CC0),(@isaienkov2025) lo que significa que se puede usar libremente con fines educativos, de análisis y sin restricciones. Además, todos los datos han sido recolectados de forma anónima a partir de informes de la propia máquina expendedora.


