<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Capítulo 3 Métodos de Holt-Winters y Suavizamiento Exponencial (Suavizamiento Exponencial Triple) | Pronóstico de Ventas de Café en Máquinas Expendedoras</title>
  <meta name="description" content="<p>This is a minimal example of using the bookdown package to write a book.
set in the _output.yml file.
The HTML output format for this example is bookdown::gitbook,</p>" />
  <meta name="generator" content="bookdown 0.42 and GitBook 2.6.7" />

  <meta property="og:title" content="Capítulo 3 Métodos de Holt-Winters y Suavizamiento Exponencial (Suavizamiento Exponencial Triple) | Pronóstico de Ventas de Café en Máquinas Expendedoras" />
  <meta property="og:type" content="book" />
  
  <meta property="og:description" content="<p>This is a minimal example of using the bookdown package to write a book.
set in the _output.yml file.
The HTML output format for this example is bookdown::gitbook,</p>" />
  <meta name="github-repo" content="rstudio/bookdown-demo" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Capítulo 3 Métodos de Holt-Winters y Suavizamiento Exponencial (Suavizamiento Exponencial Triple) | Pronóstico de Ventas de Café en Máquinas Expendedoras" />
  
  <meta name="twitter:description" content="<p>This is a minimal example of using the bookdown package to write a book.
set in the _output.yml file.
The HTML output format for this example is bookdown::gitbook,</p>" />
  

<meta name="author" content="Luisa Angélica Isaza Sanabria - Juan Andrés Murillo Cadena - Carlos Fabián Villa Infante" />


<meta name="date" content="2025-05-09" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="análisis-grafico-de-series-de-tiempo.html"/>

<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>



<style type="text/css">
  
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
</style>
<style type="text/css">
/* Used with Pandoc 2.11+ new --citeproc when CSL is used */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">A Minimal Book Example</a></li>

<li class="divider"></li>
<li class="chapter" data-level="1" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i><b>1</b> Introducción</a>
<ul>
<li class="chapter" data-level="1.1" data-path="index.html"><a href="index.html#justificación-de-la-elección"><i class="fa fa-check"></i><b>1.1</b> Justificación de la Elección</a></li>
<li class="chapter" data-level="1.2" data-path="index.html"><a href="index.html#descripción-de-la-información-a-utilizar"><i class="fa fa-check"></i><b>1.2</b> Descripción de la Información a Utilizar</a></li>
<li class="chapter" data-level="1.3" data-path="index.html"><a href="index.html#fuentes-y-permisos-de-uso"><i class="fa fa-check"></i><b>1.3</b> Fuentes y Permisos de Uso</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="análisis-grafico-de-series-de-tiempo.html"><a href="análisis-grafico-de-series-de-tiempo.html"><i class="fa fa-check"></i><b>2</b> Análisis grafico de series de tiempo</a>
<ul>
<li class="chapter" data-level="2.1" data-path="análisis-grafico-de-series-de-tiempo.html"><a href="análisis-grafico-de-series-de-tiempo.html#metodología"><i class="fa fa-check"></i><b>2.1</b> Metodología</a>
<ul>
<li class="chapter" data-level="2.1.1" data-path="análisis-grafico-de-series-de-tiempo.html"><a href="análisis-grafico-de-series-de-tiempo.html#datos"><i class="fa fa-check"></i><b>2.1.1</b> Datos</a></li>
<li class="chapter" data-level="2.1.2" data-path="análisis-grafico-de-series-de-tiempo.html"><a href="análisis-grafico-de-series-de-tiempo.html#promedio-móvil"><i class="fa fa-check"></i><b>2.1.2</b> Promedio móvil</a></li>
<li class="chapter" data-level="2.1.3" data-path="análisis-grafico-de-series-de-tiempo.html"><a href="análisis-grafico-de-series-de-tiempo.html#función-de-autocorrelación-acf"><i class="fa fa-check"></i><b>2.1.3</b> Función de Autocorrelación (ACF)</a></li>
<li class="chapter" data-level="2.1.4" data-path="análisis-grafico-de-series-de-tiempo.html"><a href="análisis-grafico-de-series-de-tiempo.html#descomposición-stl"><i class="fa fa-check"></i><b>2.1.4</b> Descomposición STL</a></li>
</ul></li>
<li class="chapter" data-level="2.2" data-path="análisis-grafico-de-series-de-tiempo.html"><a href="análisis-grafico-de-series-de-tiempo.html#estacionariedad-diferenciación-y-transformaciones"><i class="fa fa-check"></i><b>2.2</b> Estacionariedad, Diferenciación y Transformaciones</a>
<ul>
<li class="chapter" data-level="2.2.1" data-path="análisis-grafico-de-series-de-tiempo.html"><a href="análisis-grafico-de-series-de-tiempo.html#análisis-de-estacionariedad"><i class="fa fa-check"></i><b>2.2.1</b> Análisis de Estacionariedad</a></li>
<li class="chapter" data-level="2.2.2" data-path="análisis-grafico-de-series-de-tiempo.html"><a href="análisis-grafico-de-series-de-tiempo.html#diferenciación"><i class="fa fa-check"></i><b>2.2.2</b> Diferenciación</a></li>
<li class="chapter" data-level="2.2.3" data-path="análisis-grafico-de-series-de-tiempo.html"><a href="análisis-grafico-de-series-de-tiempo.html#transformaciones"><i class="fa fa-check"></i><b>2.2.3</b> Transformaciones</a></li>
<li class="chapter" data-level="2.2.4" data-path="análisis-grafico-de-series-de-tiempo.html"><a href="análisis-grafico-de-series-de-tiempo.html#justificación"><i class="fa fa-check"></i><b>2.2.4</b> Justificación</a></li>
</ul></li>
<li class="chapter" data-level="2.3" data-path="análisis-grafico-de-series-de-tiempo.html"><a href="análisis-grafico-de-series-de-tiempo.html#conclusiones"><i class="fa fa-check"></i><b>2.3</b> Conclusiones</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="métodos-de-holt-winters-y-suavizamiento-exponencial-suavizamiento-exponencial-triple.html"><a href="métodos-de-holt-winters-y-suavizamiento-exponencial-suavizamiento-exponencial-triple.html"><i class="fa fa-check"></i><b>3</b> Métodos de Holt-Winters y Suavizamiento Exponencial (Suavizamiento Exponencial Triple)</a>
<ul>
<li class="chapter" data-level="3.0.1" data-path="métodos-de-holt-winters-y-suavizamiento-exponencial-suavizamiento-exponencial-triple.html"><a href="métodos-de-holt-winters-y-suavizamiento-exponencial-suavizamiento-exponencial-triple.html#suavizamiento-exponencial-simple"><i class="fa fa-check"></i><b>3.0.1</b> Suavizamiento Exponencial Simple</a></li>
<li class="chapter" data-level="3.0.2" data-path="métodos-de-holt-winters-y-suavizamiento-exponencial-suavizamiento-exponencial-triple.html"><a href="métodos-de-holt-winters-y-suavizamiento-exponencial-suavizamiento-exponencial-triple.html#holt-winters-aditivo"><i class="fa fa-check"></i><b>3.0.2</b> Holt-Winters Aditivo</a></li>
<li class="chapter" data-level="3.0.3" data-path="métodos-de-holt-winters-y-suavizamiento-exponencial-suavizamiento-exponencial-triple.html"><a href="métodos-de-holt-winters-y-suavizamiento-exponencial-suavizamiento-exponencial-triple.html#holt-winters-multiplicativo"><i class="fa fa-check"></i><b>3.0.3</b> Holt-Winters Multiplicativo</a></li>
<li class="chapter" data-level="3.0.4" data-path="métodos-de-holt-winters-y-suavizamiento-exponencial-suavizamiento-exponencial-triple.html"><a href="métodos-de-holt-winters-y-suavizamiento-exponencial-suavizamiento-exponencial-triple.html#comparación-de-modelos-holt-winters"><i class="fa fa-check"></i><b>3.0.4</b> Comparación de Modelos Holt-Winters</a></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Pronóstico de Ventas de Café en Máquinas Expendedoras</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="métodos-de-holt-winters-y-suavizamiento-exponencial-suavizamiento-exponencial-triple" class="section level1 hasAnchor" number="3">
<h1><span class="header-section-number">Capítulo 3</span> Métodos de Holt-Winters y Suavizamiento Exponencial (Suavizamiento Exponencial Triple)<a href="métodos-de-holt-winters-y-suavizamiento-exponencial-suavizamiento-exponencial-triple.html#métodos-de-holt-winters-y-suavizamiento-exponencial-suavizamiento-exponencial-triple" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<p>El método Holt-Winters modela promedio, tendencia y estacionalidad. Dado que la serie tiene un ciclo semanal y una tendencia estacional a largo plazo, se probaron los siguientes tipos de suavizamiento: exponencial simple, aditivo y multiplicativo.
Se aplican los métodos de Holt-Winters para modelar y predecir las ventas diarias para los próximos 7 días (un ciclo semanal).</p>
<div id="suavizamiento-exponencial-simple" class="section level3 hasAnchor" number="3.0.1">
<h3><span class="header-section-number">3.0.1</span> Suavizamiento Exponencial Simple<a href="métodos-de-holt-winters-y-suavizamiento-exponencial-suavizamiento-exponencial-triple.html#suavizamiento-exponencial-simple" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>El suavizamiento exponencial simple modela solo el promedio de la serie y no considera tendencia ni estacionalidad, por lo que no es ideal para la serie de tiempo que tiene ambos componentes. Se aplicó a la serie transformada log(y) para evaluar su comportamiento en una escala con varianza estabilizada.</p>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:ses-log"></span>
<img src="_main_files/figure-html/ses-log-1.png" alt="Suavizamiento Exponencial Simple" width="100%" />
<p class="caption">
Figure 3.1: Suavizamiento Exponencial Simple
</p>
</div>
<p>Como el suavizamiento exponencial simple solo modela el nivel de la serie (sin tendencia ni estacionalidad), las predicciones son esencialmente un promedio suavizado de los valores históricos. En la escala logarítmica, las predicciones se mantienen constantes en un rango de ~5.8 a ~6 (equivalente a ~300 a ~400 en la escala original), sin reflejar el ciclo semanal ni la tendencia estacional.</p>
<p>La gráfica evidencia que este modelo no captura los patrones semanales (como mayores ventas los fines de semana) ni la tendencia estacional a largo plazo.</p>
</div>
<div id="holt-winters-aditivo" class="section level3 hasAnchor" number="3.0.2">
<h3><span class="header-section-number">3.0.2</span> Holt-Winters Aditivo<a href="métodos-de-holt-winters-y-suavizamiento-exponencial-suavizamiento-exponencial-triple.html#holt-winters-aditivo" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>En el modelo aditivo, la estacionalidad tiene una amplitud constante, lo que es consistente con la componente estacional de la descomposición STL (oscilando entre -20 y 20).</p>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:hw-additive"></span>
<img src="_main_files/figure-html/hw-additive-1.png" alt="Holt-Winters Aditivo" width="100%" />
<p class="caption">
Figure 3.2: Holt-Winters Aditivo
</p>
</div>
<p>El pronóstico refleja el ciclo semanal identificado previamente. Por ejemplo, si los fines de semana (sábado y domingo) tienen históricamente ventas más altas, el pronóstico para el 3 y 4 de mayo (sábado y domingo) debería mostrar un aumento en comparación con los días laborales.</p>
<p>Estacionalidad constante: Como el modelo es aditivo, la amplitud de las fluctuaciones estacionales es constante, lo que coincide con la descomposición STL (estacionalidad entre -20 y 20). Esto significa que los picos y caídas en las ventas (por ejemplo, fines de semana vs. días laborales) tienen una diferencia fija en valor absoluto.</p>
</div>
<div id="holt-winters-multiplicativo" class="section level3 hasAnchor" number="3.0.3">
<h3><span class="header-section-number">3.0.3</span> Holt-Winters Multiplicativo<a href="métodos-de-holt-winters-y-suavizamiento-exponencial-suavizamiento-exponencial-triple.html#holt-winters-multiplicativo" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>En el modelo multiplicativo, la amplitud de la estacionalidad varía con el nivel de la serie. Esto podría ser relevante dado que las fluctuaciones son más grandes en periodos de ventas altas (como octubre).</p>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:hw-multiplicative"></span>
<img src="_main_files/figure-html/hw-multiplicative-1.png" alt="Holt-Winters Multiplicativo" width="100%" />
<p class="caption">
Figure 3.3: Holt-Winters Multiplicativo
</p>
</div>
<p>Patrón semanal: El pronóstico refleja el ciclo semanal identificado previamente (frecuencia = 7). Por ejemplo, si los fines de semana (sábado y domingo) tienen históricamente ventas más altas, el pronóstico para el 3 y 4 de mayo (sábado y domingo) debería mostrar un aumento en comparación con los días laborales.</p>
<p>Estacionalidad constante: Como el modelo es aditivo, la amplitud de las fluctuaciones estacionales es constante, lo que coincide con la descomposición STL (estacionalidad entre -20 y 20). Esto significa que los picos y caídas en las ventas (por ejemplo, fines de semana vs. días laborales) tienen una diferencia fija en valor absoluto.</p>
</div>
<div id="comparación-de-modelos-holt-winters" class="section level3 hasAnchor" number="3.0.4">
<h3><span class="header-section-number">3.0.4</span> Comparación de Modelos Holt-Winters<a href="métodos-de-holt-winters-y-suavizamiento-exponencial-suavizamiento-exponencial-triple.html#comparación-de-modelos-holt-winters" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Comparamos la precisión de los modelos aditivo y multiplicativo usando el error cuadrático medio (RMSE) y el error absoluto medio (MAE):</p>
<pre><code>##                    RMSE      MAE
## Additive       140.4213 111.8802
## Multiplicative 143.8373 115.8820</code></pre>
<p>Con base en los resultados proporcionados:
Holt-Winters Aditivo: RMSE = 140.4213, MAE = 111.8802</p>
<p>Holt-Winters Multiplicativo: RMSE = 143.8373, MAE = 115.8820</p>
<p>El modelo Holt-Winters Aditivo es el mejor, ya que tiene un RMSE y un MAE más bajos en comparación con el modelo Holt-Winters Multiplicativo. Esto indica que el modelo aditivo tiene un mejor ajuste a los datos y comete errores de predicción más pequeños en promedio.
Diferencia en RMSE: El RMSE del modelo aditivo (140.4213) es aproximadamente 3.42 unidades menor que el del modelo multiplicativo (143.8373). El RMSE mide el error cuadrático medio, dando más peso a errores grandes, por lo que un valor más bajo sugiere que el modelo aditivo tiene menos errores grandes en sus predicciones.</p>
<p>Diferencia en MAE: El MAE del modelo aditivo (111.8802) es aproximadamente 4 unidades menor que el del modelo multiplicativo (115.8820). El MAE mide el error absoluto medio, reflejando el error promedio sin considerar la magnitud de los errores de forma cuadrática, y un valor más bajo indica que el modelo aditivo tiene un mejor rendimiento promedio.</p>
<p>Además, la descomposición STL mostró que la estacionalidad de las ventas tiene una amplitud constante (oscilando entre -20 y 20), lo que favorece al modelo aditivo, ya que este asume una estacionalidad constante, mientras que el modelo multiplicativo asume que la estacionalidad varía con el nivel de la serie. Dado que las ventas en abril de 2025 (~400) no presentan variaciones extremas que resalten las diferencias entre los modelos, el modelo aditivo es más adecuado para capturar los patrones observados.
¿Por qué se tomaron estas dos medidas (RMSE y MAE)?
RMSE (Root Mean Squared Error): El RMSE mide la raíz del promedio de los errores al cuadrado. Es útil porque:
Penaliza más los errores grandes (al elevarlos al cuadrado), lo que lo hace sensible a valores atípicos. Esto es importante en el contexto de las ventas, ya que errores grandes en la predicción (por ejemplo, subestimar un día de alta demanda como el fin de semana) podrían tener un impacto significativo en la planificación del inventario.</p>
<p>Proporciona una medida de error en las mismas unidades que la variable original (ventas en unidades monetarias), facilitando la interpretación del error.</p>
<p>MAE (Mean Absolute Error): El MAE mide el promedio de los errores absolutos, sin elevarlos al cuadrado. Es útil porque:
Representa el error promedio de las predicciones de manera directa, sin dar mayor peso a errores grandes, lo que lo hace más robusto frente a valores atípicos.</p>
<p>Es fácil de interpretar, ya que indica el error promedio en las mismas unidades que la variable original. En este caso, un MAE de 111.8802 para el modelo aditivo significa que, en promedio, las predicciones se desvían en ~111.88 unidades monetarias por día.</p>
<p>Ambas medidas se utilizan juntas porque se complementan: el RMSE destaca el impacto de errores grandes, mientras que el MAE proporciona una visión más equilibrada del error promedio. En este caso, ambas métricas coinciden en que el modelo aditivo tiene un mejor desempeño, lo que refuerza la elección de este modelo para las predicciones.</p>
<ol start="5" style="list-style-type: decimal">
<li><strong>Holt-Winters</strong>:
<ul>
<li><strong>Holt-Winters Aditivo</strong>: La gráfica de pronóstico (últimos 7 días reales del 24 al 30 de abril de 2025 y pronóstico del 1 al 7 de mayo de 2025) muestra que el modelo captura bien el ciclo semanal, reflejando patrones como mayores ventas los fines de semana (por ejemplo, 3 y 4 de mayo). La estacionalidad tiene una amplitud constante, lo que es consistente con la descomposición STL (oscilaciones entre -20 y 20). Los intervalos de confianza son relativamente estrechos, indicando buena certeza en las predicciones, aunque la alta variabilidad residual podría generar desviaciones.</li>
<li><strong>Holt-Winters Multiplicativo</strong>: Similar al modelo aditivo, captura el ciclo semanal, pero asume que la amplitud de la estacionalidad varía con el nivel de la serie. En la gráfica de pronóstico, las predicciones son cercanas a las del modelo aditivo, ya que las ventas en abril (~400) no presentan variaciones extremas que resalten las diferencias entre los modelos. Los intervalos de confianza son ligeramente más amplios en días de mayor variabilidad.</li>
<li><strong>Comparación de precisión</strong>: El modelo Holt-Winters Aditivo tiene un RMSE de 140.4213 y un MAE de 111.8802, mientras que el modelo Multiplicativo tiene un RMSE de 143.8373 y un MAE de 115.8820. El modelo aditivo es preferible, ya que tiene un RMSE y un MAE más bajos, lo que indica un mejor ajuste a los datos y errores de predicción más pequeños. El RMSE penaliza más los errores grandes, siendo útil para evitar subestimaciones en días de alta demanda, mientras que el MAE refleja el error promedio, proporcionando una visión equilibrada del rendimiento. La descomposición STL mostró que la estacionalidad es constante, lo que también favorece al modelo aditivo sobre el multiplicativo.</li>
<li><strong>Significancia de la diferencia</strong>: La diferencia entre los modelos es de 3.416 en RMSE (un aumento relativo del 2.43%) y 4.0018 en MAE (un aumento relativo del 3.58%). Esta diferencia no se considera significativa, ya que es pequeña en términos relativos (menor al 5%) y absolutos (3-4 unidades frente a ventas promedio de ~400 y una variabilidad residual de ±300). En el contexto del negocio, esta diferencia tiene un impacto mínimo en la planificación del inventario o las decisiones comerciales. Para considerar una diferencia como “grande”, el aumento relativo debería ser al menos del 10% (por ejemplo, un RMSE de 154.46 o más para el modelo multiplicativo), o la diferencia absoluta debería ser de al menos 40-50 unidades (10-12.5% del promedio de ventas), ya que esto podría afectar significativamente la toma de decisiones. Dado que la diferencia es mucho menor, ambos modelos tienen un rendimiento práctico similar, aunque el aditivo sigue siendo preferible por su mejor ajuste y consistencia teórica con la estacionalidad constante.</li>
</ul></li>
</ol>

<div id="refs" class="references csl-bib-body hanging-indent" entry-spacing="0">
<div class="csl-entry">
Isaienkov, Yaroslav. 2025. <span>“Coffee Sales.”</span> Kaggle. <a href="https://www.kaggle.com/datasets/ihelon/coffee-sales">https://www.kaggle.com/datasets/ihelon/coffee-sales</a>.
</div>
</div>
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="análisis-grafico-de-series-de-tiempo.html" class="navigation navigation-prev navigation-unique" aria-label="Previous page"><i class="fa fa-angle-left"></i></a>

    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/USERNAME/REPO/edit/BRANCH/02-cross-refs.Rmd",
"text": "Edit"
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["_main.pdf", "_main.epub"],
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "section"
}
});
});
</script>

</body>

</html>
